spring:
  datasource:
    url: ${DB_URL}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: admin-ms

server:
  port: 8082

logging:
  level:
    org:
      springframework: ERROR 
    profile: 
      exception: ERROR
      
#eureka: 
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/
