server: 
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: ${DB_URL}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka: 
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/
      
logging:
  level:
    org:
      springframework: ERROR 
    profile: 
      exception: ERROR
      
zuul:
  ignored-services: "*"
  routes:
    user-ms:
      path: /user-service/**
      location: ${USER_SERVICE_URL}
    admin-ms:
      path: /admin-service/**
      location: ${ADMIN_SERVICE_URL}
    organization-ms:
      path: /organization-service/**
      location: ${ORGANIZATION_SERVICE_URL}
    employee-ms:
      path: /employee-service/**
      location: ${EMPLOYEE_SERVICE_URL}
