version: '3'

services:
    user:
        # build: ./user
        image: thakuramit148/helping-hands-user:1.0
        container_name: user
        restart: always
        expose: 
            - "8081"
        ports:
            - "8081:8081"
        depends_on: 
            - mysql-service
        links: 
            - mysql-service
        environment: 
            - MYSQL_ROOT_PASSWORD=@helping-hand@
            - DB_URL=jdbc:mysql://mysql-service:3306/helping_hand?serverTimezone=UTC

    admin:
        # build: ./admin
        image: thakuramit148/helping-hands-admin:1.0
        container_name: admin
        restart: always
        expose: 
            - "8082"
        ports:
            - "8082:8082"
        depends_on: 
            - mysql-service
        links: 
            - mysql-service
        environment: 
            - MYSQL_ROOT_PASSWORD=@helping-hand@
            - DB_URL=jdbc:mysql://mysql-service:3306/helping_hand?serverTimezone=UTC

    organization:
        # build: ./organization
        image: thakuramit148/helping-hands-organization:1.0
        container_name: organization
        restart: always
        expose: 
            - "8083"
        ports:
            - "8083:8083"
        depends_on: 
            - mysql-service
        links: 
            - mysql-service
        environment: 
            - MYSQL_ROOT_PASSWORD=@helping-hand@
            - DB_URL=jdbc:mysql://mysql-service:3306/helping_hand?serverTimezone=UTC
    
    employee:
        # build: ./employee
        image: thakuramit148/helping-hands-employee:1.0
        container_name: employee
        restart: always
        expose: 
            - "8084"
        ports:
            - "8084:8084"
        depends_on: 
            - mysql-service
        links: 
            - mysql-service
        environment: 
            - MYSQL_ROOT_PASSWORD=@helping-hand@
            - DB_URL=jdbc:mysql://mysql-service:3306/helping_hand?serverTimezone=UTC

    api-gateway:
        # build: ./api-gateway
        image: thakuramit148/helping-hands-api-gateway:1.0
        container_name: api-gateway
        restart: always
        expose: 
            - "8080"
        ports:
            - "8080:8080"
        depends_on: 
            - mysql-service
            - employee
            - organization
            - admin
            - user
        links: 
            - mysql-service
            - user
            - admin
            - organization
            - employee
        environment: 
            - DB_URL=jdbc:mysql://mysql-service:3306/helping_hand?serverTimezone=UTC
            - MYSQL_ROOT_PASSWORD=@helping-hand@
            - USER_SERVICE_URL=http://192.168.0.33:8081
            - ADMIN_SERVICE_URL=http://192.168.0.33:8082
            - ORGANIZATION_SERVICE_URL=http://192.168.0.33:8083
            - EMPLOYEE_SERVICE_URL=http://192.168.0.33:8084

    mysql-service:
        image: thakuramit148/helping-hands-db:1.0
        container_name: mysql-service
        user: 'root'
        environment: 
           - MYSQL_DATABASE=helping_hand
           - MYSQL_ROOT_PASSWORD=@helping-hand@

    frontend:
        # build: ./frontend
        image: thakuramit148/helping-hands-frontend:1.0
        container_name: frontend
        restart: always
        expose: 
            - "80"
        ports:
            - "4200:80"
        # depends_on: 
        #     - api-gateway